import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import SupabaseProvider from "@/lib/supabase/SupabaseProvider";
import { Button } from "@/components/ui/button";

const leagueSpartan = League_Spartan({
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.0/css/all.min.css"
            integrity="sha512-DxV+EoADOkOygM4IR9yXP8Sb2qwgidEmeqAEmDKIOfPRQZOWbXCzLC6vjbZyy0vPisbH2SyW27+ddLVCN+OMzQ=="
            crossOrigin="anonymous"
            referrerPolicy="no-referrer"
          />
        </head>
        <SupabaseProvider>
          <body
            className={`${leagueSpartan.className} antialiased bg-secondary text-white`}
          >
            <header className="flex justify-end items-center p-4 gap-4 h-16 w-full bg-secondary">
              <SignedOut>
                <SignInButton />
                <SignUpButton>
                  <Button>Sign Up</Button>
                </SignUpButton>
              </SignedOut>
              <SignedIn>
                <UserButton />
              </SignedIn>
            </header>
            {children}
          </body>
        </SupabaseProvider>
      </html>
    </ClerkProvider>
  );
}
